/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.list_dangnhap;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hello Kiên
 */
public class dang_nhap extends javax.swing.JInternalFrame {

    /**
     * Creates new form dang_nhap
     */
    protected ArrayList<list_dangnhap> listDN;
    protected String url, dbUsername, dbPassword;

    public dang_nhap() {
        initComponents();
        this.url = "jdbc:sqlserver://localhost:1433;databaseName=QLBH";
        this.dbUsername = "sa";
        this.dbPassword = "111111";
        this.listDN = new ArrayList<list_dangnhap>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ckRemember = new javax.swing.JCheckBox();
        btnDangnhap = new javax.swing.JButton();
        btnDangki = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setText("USERNAME:");

        jLabel3.setText("PASSWORD:");

        ckRemember.setText("Remember?");

        btnDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_dangnhap.png"))); // NOI18N
        btnDangnhap.setText("Đăng nhập");
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });

        btnDangki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_dangky.png"))); // NOI18N
        btnDangki.setText("Đăng kí");
        btnDangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(49, 49, 49)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ckRemember)
                                    .addComponent(txtPassword)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(btnDangnhap)
                        .addGap(38, 38, 38)
                        .addComponent(btnDangki)))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDangki, btnDangnhap});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUsername});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(ckRemember)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangnhap)
                    .addComponent(btnDangki))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    protected ArrayList<list_dangnhap> festList() {
        ArrayList<list_dangnhap> result = new ArrayList<list_dangnhap>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection(this.url, this.dbUsername, this.dbPassword);
            Statement st = conn.createStatement();

            String query = "select*from NHANVIEN where username like N'%" + txtUsername.getText() + "%' and passwords like N'%" + txtPassword.getText() + "%'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                String tenNV = rs.getString("tenNV");
                String maNV = rs.getString("maNV");
                String username = rs.getString("username");
                String passwords = rs.getString("passwords");
                result.add(new list_dangnhap(tenNV, maNV, username, passwords));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dang_nhap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dang_nhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        return result;
    }
    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapActionPerformed
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập username");
            txtUsername.requestFocus();
            return;
        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập password");
            txtPassword.requestFocus();
            return;
        }

        this.listDN = this.festList();
        if (listDN.size() <= 0) {
            JOptionPane.showMessageDialog(this, "mật khẩu hoặc tài khoản không đúng , nhập lại");
            txtUsername.requestFocus();
            return;
        } else {
            if (ckRemember.isSelected()) {
                JOptionPane.showMessageDialog(this, "Đã ghi nhớ!");
            }
            JOptionPane.showMessageDialog(this, "đăng nhập thành công");
            for (list_dangnhap dn : listDN) {
                Trang_chu_ban_hang.nhanvien = dn.getTenNV();
                Trang_chu_ban_hang.MaNV = dn.getMaNV();
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnDangnhapActionPerformed

    private void btnDangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkiActionPerformed
        FrmDangKi dk = new FrmDangKi();
        dk.setVisible(true);

        dk.setDefaultCloseOperation(dang_nhap.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDangkiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangki;
    private javax.swing.JButton btnDangnhap;
    private javax.swing.JCheckBox ckRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
